#create the image of igluco
FROM wangkai/node_bs_4.5.0
MAINTAINER wangkai/wkcmys@126.com
COPY iGlucoAppV1/config /usr/src/
WORKDIR /usr/src/iGlucoAppV1
CMD pm2 start app.js --name iGlucoAppV1 && pm2 logs




